const capitals = [
    "Abu Dhabi",
    "Abuja",
    "Accra",
    "Addis Ababa",
    "Algiers",
    "Amman",
    "Amsterdam",
    "Ankara",
    "Antananarivo",
    "Apia",
    "Ashgabat",
    "Asmara",
    "Astana",
    "Asunción",
    "Athens",
    "Baghdad",
    "Baku",
    "Bamako",
    "Bandar Seri Begawan",
    "Bangkok",
    "Bangui",
    "Banjul",
    "Basseterre",
    "Beijing",
    "Beirut",
    "Belgrade",
    "Belmopan",
    "Berlin",
    "Bern",
    "Bishkek",
    "Bissau",
    "Bogotá",
    "Brasília",
    "Bratislava",
    "Brazzaville",
    "Bridgetown",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Buenos Aires",
    "Bujumbura",
    "Cairo",
    "Canberra",
    "Caracas",
    "Castries",
    "Copenhagen",
    "Chicago",
    "Dakar",
    "Damascus",
    "Dhaka",
    "Dili",
    "Djibouti",
    "Dodoma",
    "Doha",
    "Dublin",
    "Dushanbe",
    "Edinburgh",
    "Funafuti",
    "Gaborone",
    "George Town",
    "Georgetown",
    "Hanoi",
    "Harare",
    "Havana",
    "Helsinki",
    "Honolulu",
    "Islamabad",
    "Jakarta",
    "Jamestown",
    "Jerusalem",
    "Kabul",
    "Kampala",
    "Kathmandu",
    "Khartoum",
    "Kiev",
    "Kigali",
    "Kingston",
    "Kinshasa",
    "Kuala Lumpur",
    "Kuwait City",
    "Libreville",
    "Lilongwe",
    "Lima",
    "Lisbon",
    "Ljubljana",
    "Lomé",
    "London",
    "Luanda",
    "Lusaka",
    "Luxembourg",
    "Madrid",
    "Majuro",
    "Malabo",
    "Malé",
    "Managua",
    "Manama",
    "Manila",
    "Maputo",
    "Maseru",
    "Mbabane",
    "Melekeok",
    "Mexico City",
    "Minsk",
    "Mogadishu",
    "Monaco",
    "Monrovia",
    "Montevideo",
    "Moroni",
    "Moscow",
    "Muscat",
    "Nairobi",
    "Nassau",
    "Naypyidaw",
    "N'Djamena",
    "New Delhi",
    "Niamey",
    "Nicosia",
    "Nouakchott",
    "Nouméa",
    "Nuku'alofa",
    "Nuuk",
    "Oslo",
    "Ottawa",
    "Ouagadougou",
    "Pago Pago",
    "Palikir",
    "Panama City",
    "Papeete",
    "Paramaribo",
    "Paris",
    "Phnom Penh",
    "Podgorica",
    "Port Louis",
    "Port Moresby",
    "Port Vila",
    "Port-au-Prince",
    "Porto-Novo",
    "Prague",
    "Praia",
    "Pretoria",
    "Pristina",
    "Pyongyang",
    "Quito",
    "Rabat",
    "Ramallah",
    "Reykjavík",
    "Riga",
    "Riyadh",
    "Rome",
    "Roseau",
    "Saint George's",
    "Saint John's",
    "Saint Peter Port",
    "Saint-Denis",
    "San José",
    "San Juan",
    "San Marino",
    "San Salvador",
    "Sana'a",
    "Santiago",
    "Santo Domingo",
    "São Tomé",
    "Sarajevo",
    "Skopje",
    "Sofia",
    "Sri Jayawardenepura Kotte",
    "Stockholm",
    "Sucre",
    "Suva",
    "Taipei",
    "Tallinn",
    "Tarawa",
    "Tashkent",
    "Tbilisi",
    "Tegucigalpa",
    "Tehran",
    "Thimphu",
    "Tirana",
    "Tokyo",
    "Tripoli",
    "Tunis",
    "Ulaanbaatar",
    "Vaduz",
    "Valletta",
    "Vatican City",
    "Victoria",
    "Vienna",
    "Vientiane",
    "Vilnius",
    "Warsaw",
    "Washington, D.C.",
    "Wellington",
    "Windhoek",
    "Yaoundé",
    "Yerevan",
    "Zagreb",


    "Vác",
    "Győr",
    "Debrecen",
    "Pécs",
    "Szeged",
    "Eger",
    "Kecskemét",
    "Miskolc",
    "Székesfehérvár",
    "Tatabánya",
    "Zalaegerszeg",
    "Békéscsaba",
    "Nyíregyháza",
    "Sopron",
    "Szombathely",
    "Kaposvár",
    "Veszprém",
    "Dunaújváros",
    "Siófok",
    "Hódmezővásárhely",

];

export default capitals;
